### PR TITLE
create error

### PR DESCRIPTION
**Pull request by jirawat001**

### CODE REVIEW

**Comment by jirawat001** [comment]
I want to merge :(

**Comment by jirawat001** [comment]
Any chance of getting this merged?

**Comment by dominikh** [comment]
Considering it is doing nothing useful and just mutilates a test case? No. What exactly is it you're hoping to achieve by sending dozens of pointless, broken PRs to random projects?

**Comment by jirawat001** [comment]
okay,I 'm sorry

**Pull request closed without merging**
