### PR TITLE
Add section about using as a Git pre-commit hook

### PR DESCRIPTION
**Pull request by lencioni**
overcommit is a fully configurable and extendable Git hook manager that
includes out-of-the-box support for running golint as a Git pre-commit
hook.

### CODE REVIEW

**Comment by dsymonds** [comment]
No thanks. As per the text higher in the same file, golint is not suited for automatic use in this kind of way.

**Comment by lencioni** [comment]
Cool, no worries. Thanks for considering it.

I'm not much of a Go developer, and I haven't really been involved with the golint overcommit integration (that was mostly @sectioneight and @jawshooah), but I'd like to make sure I understand what you mean. Are you referring to this text?

> ...this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process.

**Comment by dsymonds** [comment]
That and all that surrounds it, yes.

**Comment by lencioni** [comment]
I have read the entire document a number of times now and I am still having a difficult time understanding how running golint as a Git pre-commit hook is any different than integrating it with your editor. Will you help me understand?

**Pull request closed without merging**
