### PR TITLE
Allow me as a receiver name

### PR DESCRIPTION
**Pull request by twpayne**
This supersedes #212.

### CODE REVIEW

**Comment by dsnet** [comment]
Can you sign the CLA?

**Comment by dsnet** [comment]
I'm not sure why the GoogleBot didn't trigger. The message it sends is as follows:

---

Thanks for your pull request.  It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit <https://cla.developers.google.com/> to sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify.  Thanks.

---

- If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
- If you signed the CLA as a corporation, please let us know the company's name.

**Comment by twpayne** [comment]
I signed it!

Note that I signed the CLA previously (early 2012) and that I was working for Google when I created this PR so technically the IP is already Google's property.

**Comment by dsnet** [comment]
Merged as 64229b89515c2a585c623c79a7ccdea71e8589ff

**Pull request closed without merging**
