### PR TITLE
Adding a suggested name for the ALL_CAPS warning

### PR DESCRIPTION
**Pull request by msoap**
Old warning is:
    yandex-weather.go:52:2: don't use ALL_CAPS in Go names; use CamelCase

New warning is:
    yandex-weather.go:52:2: don't use ALL_CAPS in Go names; const BASE_URL should be BaseURL

### CODE REVIEW

**Comment by msoap** [comment]
So, this changes useful for generate script with `gofmt -w -r` for fix warnings:

```
golint | perl -nE 'if (/^ ([^:]+) .+ \s+ (\w+) \s+ should \s+ be \s+ (\w+)$/x) {say qq/gofmt -w -r "$2 -> $3" $1/}' | sort | uniq
```

**Comment by dsymonds** [comment]
Sorry, this isn't handling tons of other cases, like MORE_THAN_TWO_WORDS, or THING_URL, or some others. I don't think it's going to be easy enough to get it accurate enough.

**Comment by msoap** [comment]
Why? Seems that handles:

```sh
$ cat p.go
package main

// MORE_THAN_TWO_WORDS - two
const MORE_THAN_TWO_WORDS = "two words"

// THING_URL - url
var THING_URL = "https://github.com/golang/lint/pull/197"

func main() {
	println(MORE_THAN_TWO_WORDS, THING_URL)
}
```

```
$ golint p.go

p.go:4:7: don't use ALL_CAPS in Go names; const MORE_THAN_TWO_WORDS should be MoreThanTwoWords
p.go:7:5: don't use ALL_CAPS in Go names; var THING_URL should be ThingURL
```

The algorithm is as follows:
`"THING_URL" -> "Thing_url" -> lintName("Thing_url") -> "ThingURL"`

**Comment by dsymonds** [comment]
Ah, I see. Let me think about this.

**Comment by msoap** [comment]
@dsymonds @dsnet ping

**Comment by andybons** [comment]
@googlebot cla?

**Pull request closed without merging**
