### PR TITLE
Support mix of files, directories and packages

### PR DESCRIPTION
**Pull request by Horgix**
Currently, it is only possible to lint files, directories, OR packages, not a mix of them, which is a bit surprising when encounted.

This PR adds support for linting a mix of files, directories and packages given in arguments to `golint`.

### CODE REVIEW

**Comment by Horgix** [comment]
I signed it!

**Comment by Horgix** [comment]
Any chance to have some feedback on this?

**Comment by Horgix** [comment]
Ping? :slightly_smiling_face:

**Comment by andybons** [comment]
Does the `go` tool behave in the same way?

**Comment by Horgix** [comment]
@andybons :
> Does the go tool behave in the same way?

`Gofmt` does behave in the same way and is actually what inspired me to submit this PR since I became used to it and ended up being surprised by `golint` not behaving the same way.
However, `go fmt` only takes packages, no files or directories whatsoever, so it's hard to compare.

See [line 213 of gofmt.go](https://golang.org/src/cmd/gofmt/gofmt.go) for comparison: it just loops on every path argument and work on it, kinda like this PR does.

**Comment by Horgix** [comment]
Any news on this? Could I help with something? :slightly_smiling_face:

**Pull request closed without merging**
