### PR TITLE
Add XMPP to the list of common initialisms

### PR DESCRIPTION
**Pull request by froodian**

### CODE REVIEW

**Comment by dsnet** [comment]
I'm not sure why the GoogleBot didn't trigger. The message it sends is as follows:

---

Thanks for your pull request.  It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit <https://cla.developers.google.com/> to sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify.  Thanks.

---

- If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
- If you signed the CLA as a corporation, please let us know the company's name.

**Comment by froodian** [comment]
I signed it!

**Comment by dsnet** [comment]
Just wondering, did you register your github account when you signed the  CLA? I can't seem to verify that you've signed the CLA.

**Comment by froodian** [comment]
My employer actually signed it on my behalf using a google group that I'm part of.  When I go to the https://cla.developers.google.com/clas page I see `Google Corporate CLA	Appboy Inc.	Sep 22, 2016 12:24 PDT`

**Comment by dsnet** [comment]
Merged as 55ae771cfa82f3846897c972e262ed5d54d47d48

**Pull request closed without merging**
