### PR TITLE
golint: suggest `for range` when possible

### PR DESCRIPTION
**Pull request by dominikh**
for _ = range and for _, _ = range can be written as 
for range instead.

### CODE REVIEW

**Comment by dsymonds** [comment]
Thanks, but I'm not convinced this is particularly useful. `for _ = range` was the only option for so long and is only able to be shortened relatively recently, so it's hard to argue that the shorter form is stylistically dominant.

**Comment by dominikh** [comment]
"relatively recently" was over a year ago. I was hoping that adding the check would remind people that this is now possible. I think most people don't realize that it is. 

It's something that `gofmt -s` simplifies (just like `for x, _ := range`), so it seemed to fit in for symmetry's sake.

**Comment by dsymonds** [comment]
A year isn't much time in the scheme of things to make something a standard. Go has been a public project for over 6 years. Mere availability of a language construct does not make it stylistically _wrong_ to use the longer form, and it's not golint's place to remind people of new features, only to flag poor style.

Sorry, this doesn't pass muster.

**Comment by dominikh** [comment]
Fair enough. I'll be back in a year ;-)

**Comment by louwers** [comment]
@dominikh Here we are.

**Comment by dominikh** [comment]
I am impressed. PTAL

**Comment by andybons** [comment]
@dominikh can you reply to @googlebot ?

**Comment by dominikh** [comment]
I signed it.

**Comment by andybons** [comment]
@googlebot cla?

**Comment by andybons** [comment]
Hm. @googlebot seems stuck. Can you confirm with your existing CLA data and verify that your email is set on your git commits? Links in https://github.com/golang/lint/pull/196#issuecomment-286777711

**Comment by dominikh** [comment]
I think I see what happened. I had signed the CLA on my gmail account a long time ago, and added my main email (dominik@honnef.co) as an alternate email address. A while back, I turned dominik@honnef.co into a Google Apps account, so it must've detached the address from the CLA. 

I have now effectively signed a second CLA, on the new account.

**Pull request closed without merging**
